language: php

# Distrubution / environments: https://docs.travis-ci.com/user/reference/overview/
# Ubuntu Trusty does not support php8: https://docs.travis-ci.com/user/languages/php/
dist: xenial

notifications:
  email:
    on_success: never
    on_failure: change

language: node_js
node_js:
  - "8.12.0"

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 7.4
      before_script:
        - yarn
        - composer install -o
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION


script:
  - phpunit --debug
  - yarn run js-lint
